version: '3.3'
services:
  fake_api:
    image: jaxgeller/lwan
    volumes:
      - ./../../data:/lwan/wwwroot
    ports:
      - 8000:8080
    networks:
      - kong
  kong:
    build:
      context: ./
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: kong.yml
    ports:
      - 8080:8000
    networks:
      - kong

networks:
  kong:
